# Generated by Django 5.2.2 on 2025-06-07 14:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime_app', '0002_rename_user_details_user_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_detail',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user_detail',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
